#!/usr/bin/env python
import sys
sys.path.insert(1, '/usr/share/m2ee-tools')

import m2ee as m2ee_api
import logging

logger = logging.getLogger("m2ee")
logger.setLevel(50)

try:
    m2ee = m2ee_api.M2EE()
except TypeError:
    (_, config) = m2ee_api.config.read_yaml_files()
    m2ee = m2ee_api.M2EE(config=config)

health = m2ee_api.nagios.check_health(m2ee.runner, m2ee.client)
sys.exit(health)
