#!/usr/bin/python

from __future__ import print_function
import sys
import requests

STATE_OK = 0
STATE_CRITICAL = 2

state = STATE_OK
state_label = "OK"

response = requests.get('http://localhost:83/health?servername=%s' % sys.argv[1])

if response.status_code != 200:
    state = STATE_CRITICAL
    state_label = "CRITICAL"

print("%s - %s" % (state_label, response.json()['message']))
exit(state)
