#!/usr/bin/python3

import logging
import m2ee
import sys

logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)
consolelogformatter = logging.Formatter("%(levelname)s: %(message)s")
stderrlog = logging.StreamHandler(sys.stderr)
stderrlog.setFormatter(consolelogformatter)
logger.addHandler(stderrlog)

m2 = m2ee.M2EE()
state, message, loglines = m2ee.nagios.check_critical_logs(m2.client)
print(message)
if loglines is not None:
    print('\n'.join(loglines))
sys.exit(state)
