#!/bin/sh

prod_user=$1
failover_user=$2
maxage=$3

if [ -z $prod_user ] || [ -z $failover_user ]; then
    echo "usage $0 <prod_user> <failover_user> [max age in seconds]"
    exit 1
fi

if ! id -u $prod_user >/dev/null 2>&1; then
    echo "Production wal user $prod_user does not exist"
    exit 1
fi

if ! id -u $failover_user >/dev/null 2>&1; then
    echo "Production wal user $failover_user does not exist"
    exit 1
fi

if [ -z $maxage ]; then
    maxage=7200
fi

last_wal_in_backlog=$(ls -1rt /var/spool/postgresql/backlog/$prod_user/ /var/spool/postgresql/backlog/$failover_user/ | tail -1 | xargs -i find /var/spool/postgresql/backlog/$prod_user/ /var/spool/postgresql/backlog/$failover_user/ -name "{}")

basename_last_wal_in_backlog=$(basename $last_wal_in_backlog)

if [ ! -f $last_wal_in_backlog ]; then
    echo "$last_wal_in_backlog WAL not found in backlog"
    exit 2
fi

# file age in seconds = current_time - file_modification_time.
fileage=$(($(date +%s) - $(stat -c '%Y' "$last_wal_in_backlog")))
test $fileage -lt $maxage && {
    echo "OK: Received $basename_last_wal_in_backlog $fileage seconds ago (threshold: $maxage seconds)."
    exit 0
}
echo "CRITICAL: No new WAL in backlog for at least $maxage seconds. Last: $basename_last_wal_in_backlog ($fileage seconds ago)."
exit 2
