#!/usr/bin/python

from __future__ import print_function
import sys
import requests

STATE_OK = 0
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

state = STATE_OK
state_label = "OK"
message = ""

try:
    response = requests.get('http://localhost:83/health?servername=%s' % sys.argv[1])

    if response.status_code != 200:
        state = STATE_CRITICAL
        state_label = "CRITICAL"

    message = response.json()['message']

except requests.exceptions.RequestException as e:
    state = STATE_UNKNOWN
    state_label = "UNKNOWN"
    message = e

print("%s - %s" % (state_label, message))
exit(state)
