#!/bin/sh
FILE=/var/run/restored_logfile
MAXAGE=7200

if [ ! -f $FILE ]; then
	echo "$FILE does not exist"
	exit 2
fi

# file age in seconds = current_time - file_modification_time.
FILEAGE=$(($(date +%s) - $(stat -c '%Y' "$FILE")))
test $FILEAGE -lt $MAXAGE && {
    echo "OK: Last WAL was restored $FILEAGE seconds ago."
    exit 0
}

WALFILE=$(head -n 1 $FILE)
echo "CRITICAL: Last WAL $WALFILE restored more than $MAXAGE seconds ago ($FILEAGE seconds ago)."
exit 2
