#!/bin/sh

prod_user=$1
failover_user=$2

if [ -z $prod_user ] || [ -z $failover_user ]; then
    echo "usage $0 prod_user failover_user"
    exit 1
fi

if ! id -u $prod_user >/dev/null 2>&1; then
    echo "Production wal user $prod_user does not exist"
    exit 1
fi

if ! id -u $failover_user >/dev/null 2>&1; then
    echo "Production wal user $failover_user does not exist"
    exit 1
fi

MAXAGE=7200
last_wal_in_backlog=$(ls -1rt /var/spool/postgresql/backlog/$prod_user/ /var/spool/postgresql/backlog/$failover_user/ | tail -1)

if [ ! -f $last_wal_in_backlog ]; then
    echo "$last_wal_in_backlog WAL not found in backlog"
    exit 2
fi

# file age in seconds = current_time - file_modification_time.
FILEAGE=$(($(date +%s) - $(stat -c '%Y' "$last_wal_in_backlog")))
test $FILEAGE -lt $MAXAGE && {
    echo "OK: Received $last_wal_in_backlog within the last $MAXAGE seconds."
    exit 0
}
echo "CRITICAL: No new WAL in backlog in the last $MAXAGE seconds. Last: $last_wal_in_backlog"
exit 2
