#!/usr/bin/python3

import logging
import m2ee
import sys

logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)
consolelogformatter = logging.Formatter("%(levelname)s: %(message)s")
stderrlog = logging.StreamHandler(sys.stderr)
stderrlog.setFormatter(consolelogformatter)
logger.addHandler(stderrlog)

m2 = m2ee.M2EE()
state, message = m2ee.nagios.check_license(m2.client)
print(message)
sys.exit(state)
