#!/usr/bin/python3

import sys
import requests

STATE_OK = 0
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

state = STATE_OK
state_label = "OK"
message = ""

fqdn = sys.argv[1]

try:
    response = requests.get('http://localhost:83/keystore/find?fqdn=%s' % fqdn)

    try:
        if response.json()[fqdn]["keystore"]["crt"] is False or \
           response.json()[fqdn]["keystore"]["key"] is False:
            state = STATE_CRITICAL
            state_label = "CRITICAL"

        message = "%s: CRT found: %s, KEY found: %s" % (
            sys.argv[1],
            response.json()[fqdn]["keystore"]["crt"],
            response.json()[fqdn]["keystore"]["key"],
        )
    except ValueError as e:
        state = STATE_UNKNOWN
        state_label = "UNKNOWN"
        message = "HTTP %s - %s" % (response.status_code, e)

except requests.exceptions.RequestException as e:
    state = STATE_UNKNOWN
    state_label = "UNKNOWN"
    message = e

print("%s - %s" % (state_label, message))
exit(state)
