#!/bin/sh
FILE=/var/run/restored_logfile
MAXAGE=7200

if [ ! -f $FILE ]; then
	echo "$FILE does not exist"
	exit 2
fi

# file age in seconds = current_time - file_modification_time.
FILEAGE=$(($(date +%s) - $(stat -c '%Y' "$FILE")))
test $FILEAGE -lt $MAXAGE && {
    echo "$FILE is less than $MAXAGE seconds old."
    exit 0
}
echo "$FILE is older than $MAXAGE seconds."
exit 2
